id: P009597
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB4566
  title: སྨན་བླའི་མདོ་དང་མདོ་ཆོག་ཕྱོགས་སྒྲིག་རིན་ཆེན་སྒྲོན་མེ
  author: ''
  volumes:
    24685616fea347e3b41f735c59fed944:
      image_group_id: I1PD34004
      title: ''
      volume_number: 1
      total_pages: 516
      base_file: v001.txt
