id: I77E635D3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:11:58+00:00'
last_modified: '2022-06-08T12:09:28.742394+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB4566
  title: སྨན་བླའི་མདོ་དང་མདོ་ཆོག་ཕྱོགས་སྒྲིག་རིན་ཆེན་སྒྲོན་མེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2221':
      image_group_id: I1PD34004
      title: ''
      total_pages: 516
      order: 1
      base_file: 2221.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
